// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 多对多关系;

namespace 多对多关系.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220103124128_修改dbContext属性名222")]
    partial class 修改dbContext属性名222
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentTeacher", b =>
                {
                    b.Property<long>("Students1Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Teachers2Id")
                        .HasColumnType("bigint");

                    b.HasKey("Students1Id", "Teachers2Id");

                    b.HasIndex("Teachers2Id");

                    b.ToTable("T_Teacher_Student");
                });

            modelBuilder.Entity("多对多关系.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Name")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("T_Students");
                });

            modelBuilder.Entity("多对多关系.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Name")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("T_Teacher");
                });

            modelBuilder.Entity("StudentTeacher", b =>
                {
                    b.HasOne("多对多关系.Student", null)
                        .WithMany()
                        .HasForeignKey("Students1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("多对多关系.Teacher", null)
                        .WithMany()
                        .HasForeignKey("Teachers2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
